### ISSUE TITLE
Nxlog Agent Error

### ISSUE THREAD

**Issue by ikhabi** [lamby/pkg-nxlog-ce#3]
I keep getting this error "2016-00-00 10:00:02 ERROR not enough data to decode serialized logdata" on ,my agents.

The agents are running well but cant send logs to my Log Management system. So far i have been using a dirt fix of deleting my buffered logs and restarting the agent.
[nxlog.txt](https://github.com/lamby/pkg-nxlog-ce/files/574698/nxlog.txt)

Is this a bug or something to do with my configs?

**Comment by lamby** [comment]
Hi @ikhabi 

Unfortunately you've filed this issue against the Debian packaging of nxlog instead of nxlog itself. Was this deliberate? I'm assuming not, so closing here so you can re-raise it in a more appropriate venue.

best wishes,

Chris
