### ISSUE TITLE
NXLog Windows Packaging

### ISSUE THREAD

**Issue by wkarthik** [lamby/pkg-nxlog-ce#4]
I downloaded the pkg-nxlog-ce  source and compiled and installed in Ubuntu.

I wanted to create a Windows package from the source. So i run the script ./wininst.sh from the packaging/windows/ folder.

running the wininst.sh script is showing errors, Can you let me how to rectify this issue, 

ibtool: link: ranlib .libs/im_file.a
libtool: link: ( cd ".libs" && rm -f "im_file.la" && ln -s "../im_file.la" "im_file.la" )
make[5]: Entering directory '/pkg-nxlog-ce-master/src/modules/input/file'
make[5]: Nothing to be done for 'install-exec-am'.
test -z "//input" || /bin/mkdir -p "C:\\\\msys\\\\1.0\\\\nxlog-tmp//input"
 /bin/bash ../../../../libtool   --mode=install /usr/bin/install -c   im_file.la 'C:\\msys\\1.0\\nxlog-tmp//input'
libtool: install: /usr/bin/install -c .libs/im_file.so C:\\msys\\1.0\\nxlog-tmp//input/im_file.so
/usr/bin/install: cannot create regular file 'C:\msys\1.0\nxlog-tmp//input/im_file.so': No such file or directory
Makefile:289: recipe for target 'install-im_fileLTLIBRARIES' failed
make[5]: *** [install-im_fileLTLIBRARIES] Error 1
make[5]: Leaving directory '/pkg-nxlog-ce-master/src/modules/input/file'
Makefile:454: recipe for target 'install-am' failed
make[4]: *** [install-am] Error 2
make[4]: Leaving directory '/pkg-nxlog-ce-master/src/modules/input/file'
Makefile:286: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/pkg-nxlog-ce-master/src/modules/input'
Makefile:286: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/pkg-nxlog-ce-master/src/modules'
Makefile:286: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/pkg-nxlog-ce-master/src'
Makefile:407: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by lamby** [comment]
This repo is for the *Debian* packaging of nxlog-ce, if you are having problems with ``wininst`` I suggest you speak directly to upstream. Besides, I do not use Windows so simply cannot help you here I'm afraid. :(  Good luck!
